### ISSUE TITLE
依赖不上 aar

### ISSUE THREAD

**Issue by Sum41forever** [donglua/PhotoPicker#102]
compile 'me.iwf.photopicker:PhotoPicker:0.8.5@aar'

这个依赖不上，换成了0.8.9的就依赖上了，这个可以更新一下。
打个APK吧，google play上下APP 还要装VPN，安装的也慢。

**Comment by donglua** [comment]
https://github.com/donglua/PhotoPicker/releases/download/0.8.4/Demo.apk
