### ISSUE TITLE
图片选择回传的时候没有滑到的地方默认是不会加到选择list中去

### ISSUE THREAD

**Issue by zhoujuanjuan** [donglua/PhotoPicker#103]
问题复现步骤：
1、点开选择器向下滑动几页（只要不停留在第一页）
2、点击完成后再次进入选择器，将之前选择的pathlist传进去了
3、不要滑动到上次选择的位置，任意选择图片
4、结果会发现选择图片的列表里面没有originlist有的图片，而是现在新选择的

看代码问题出现在  将originlist 加到 selectelist 是在  SelectableAdapter   isSelected(Photo photo)方法中执行，然而这个方法，是展现的图片才会执行该方法，在下面几页的没展现的图片并不会执行，所以originlist 并没有加入到selectelist中，，，导致最后遗漏了之前选择的图片、、、

求大神优化    优化。。。。。！！！！！

**Comment by donglua** [comment]
噢，我懂你的意思了。。是有这个问题，没考虑到这个问题

**Comment by donglua** [comment]
@yunxuanyan

**Comment by yunxuanyan** [comment]
不好意思，Google转垃圾邮件了，才看到，你改了吗？没改我试试看

**Comment by yunxuanyan** [comment]
我建了一个pull request：https://github.com/donglua/PhotoPicker/pull/105

**Comment by zhoujuanjuan** [comment]
我有改，但是改出来的效果不理想，感觉整个adapter都需要改造才可以，求大神优化，优化完告知一下哈，谢谢！！！

发自我的 iPhone

> 在 2016年8月18日，15:14，yunxuanyan <notifications@github.com> 写道：
> 
> 不好意思，Google转垃圾邮件了，才看到，你改了吗？没改我试试看
>

**Comment by yunxuanyan** [comment]
已经修改完了，把selectedPhotos的类型改成string再调整一下就解决了
