### ISSUE TITLE
android 6.0的权限判断是否可以放到库里？

### ISSUE THREAD

**Issue by tingbob** [donglua/PhotoPicker#108]
android 6.0的权限判断是否可以放到库里？
如果不放到库里，是否可以增加拍照按钮的监听，可以让使用者来方便进行拍照前的camera权限判断？

**Comment by a521wangandroid** [comment]
这个提议不错，我上次就是因为安卓6.0权限的问题导致了闪退，后来手动添加的就解决了

**Comment by zhangheng12345** [comment]
@a521wangandroid 大神 如何手动添加。。。这个不是写在库源码里面的么...

**Comment by donglua** [comment]
已修改~
