### ISSUE TITLE
glide can config? add fb fresco support?

### ISSUE THREAD

**Issue by WatsonYao** [donglua/PhotoPicker#112]
只能glide加载，图片加载可以配置是否采用fresco加载吗？

**Comment by hss01248** [comment]
用fresco的话改动非常大的 @WatsonYao

**Comment by jing-wu** [comment]
我修改了一份，使用fresco，minSdk:14
https://github.com/jing-wu/PhotoPicker

**Comment by WatsonYao** [comment]
@jing-wu thanks very much~ :)
