### ISSUE TITLE
请问下大神为什么限制只能选择一次图片，选择第二次必须要把之前的给删除掉，不然调用删除图片的方法就会无效，请问下大神这是什么用意呢？

### ISSUE THREAD

**Issue by nick-zeng** [donglua/PhotoPicker#114]

**Comment by donglua** [comment]
没有这个限制吧

**Comment by nick-zeng** [comment]
你可以试一下的  我就是在你的Demo 上面改的   在onactivityresult 去掉那个 selectoedphoto.clear   然后移除图片再返回  数组的长度还是没变   然后 加上那句    就正常了

**Comment by nick-zeng** [comment]
麻烦大神修复下 这个问题呢 。。。

**Comment by donglua** [comment]
我Demo是这样写，你用的时候，不用这样写啊

**Comment by nick-zeng** [comment]
不那样写的话就删除不了图片  我也不知道怎么回事  您可以看看 真的是这样
