### ISSUE TITLE
您好三星手机使用照相功能导致程序崩溃，请问如何解决

### ISSUE THREAD

**Issue by Mars-Yu** [donglua/PhotoPicker#117]

**Comment by donglua** [comment]
6.0 吗

**Comment by heygays** [comment]
如题，我也是，Android6.0当点击摄像头图标时，没有申请权限这个动作。

**Comment by yjiang2009** [comment]
三星手机是因为照相时切换了横竖屏。所以导致Activity重启。你在拍照回调返回的Activity的mainfest里加上configchanges就好，切换横竖屏时不重建Activity。

**Comment by donglua** [comment]
试试新版本~
