### ISSUE TITLE
基于你的这个库我优化了一下ui,并封装了显示的组件,你看下这些能否合并到你的主仓库里去?

### ISSUE THREAD

**Issue by hss01248** [donglua/PhotoPicker#118]
fork出来的仓库地址是:
https://github.com/glassLake/PhotoPicker

ps. 你这个库是github上我所遇到的多图选择里体验最好的库,解决了我项目中的这个大难题,多谢多谢!

**Comment by donglua** [comment]
![image](https://cloud.githubusercontent.com/assets/3875265/18374852/fa0ffda8-7682-11e6-988b-7ea33b2655c9.png)


这个改动好大，我先在 README 里放个链接让大家看到你这个版本吧
