### ISSUE TITLE
很强大，希望把图片裁剪也添加上去

### ISSUE THREAD

**Issue by codeinging** [donglua/PhotoPicker#120]

**Comment by jing-wu** [comment]
我个人倒是觉得库只负责选择图片就好。
推荐一个裁切的库：https://github.com/Yalantis/uCrop

**Comment by donglua** [comment]
选择图片回来，再决定要不要再跳转一个裁剪吧

顺手推荐几个裁剪库：

https://github.com/Yalantis/uCrop
https://github.com/IsseiAoki/SimpleCropView
https://github.com/jdamcd/android-crop
https://github.com/lyft/scissors

**Comment by hss01248** [comment]
我已经把拍照/图片选择--裁剪--压缩整个给整合起来了,链式调用即可:
https://github.com/hss01248/PhotoOut
