### ISSUE TITLE
小白一个 我把库导入项目  然后报错

### ISSUE THREAD

**Issue by fantomFire** [donglua/PhotoPicker#129]
Error:(13, 0) Could not read script 'D:\StudioWorkSpace\MyApplication1\gradle\gradle-mvn-push.gradle' as it does not exist.
这个是什么原因  怎么解决 急急急！！！！

**Comment by donglua** [comment]
稍等，我看看

**Comment by donglua** [comment]
或者你先把 ```apply from: '../gradle/gradle-mvn-push.gradle'```这句删了

**Comment by fantomFire** [comment]
你好！！ 删了之后 更新了更新了SDK  不报错
