### ISSUE TITLE
相册中不显示.bmp文件

### ISSUE THREAD

**Issue by SCNUPeiFeng** [donglua/PhotoPicker#131]
手机中有几张.bmp的图片，在选择页面中没有显示出来，是因为不支持bmp吗

**Comment by donglua** [comment]
是的，没有。因为只写了这几种 "image/jpeg", "image/png", "image/jpg","image/gif"。需要的话可以再加~

https://github.com/donglua/PhotoPicker/blob/master/PhotoPicker/src/main/java/me/iwf/photopicker/utils/PhotoDirectoryLoader.java
