### ISSUE TITLE
选择图片界面 底部的颜色

### ISSUE THREAD

**Issue by liujiangshuai** [donglua/PhotoPicker#134]
选择图片界面  底部“所有图片”所在区域 的颜色可以设置为与toolbar一致吗？

**Comment by donglua** [comment]
https://github.com/donglua/PhotoPicker/blob/master/PhotoPicker/src/main/res/layout/__picker_fragment_photo_picker.xml

你在你的```layout```目录里建一个同名的```__picker_fragment_photo_picker.xml```，自己改改，应该能覆盖原来的。

**Comment by liujiangshuai** [comment]
亲测可用，多谢啦！

**Comment by liujiangshuai** [comment]
__picker_fragment_photo_picker.xml 有个疑问为何不考虑加入这个 android:background="?attr/colorPrimary"  使底部和Toolbar颜色一致呢

**Comment by donglua** [comment]
嗯，这个可以加上

**Comment by zyaman** [comment]
不能覆盖啊，android file-based resourse names must start with a lowercase letter，必须小写字母开头，想底部文字颜色为白色,怎么做啊

**Comment by zyaman** [comment]
行了，直接找源文件可以复制进去，直接新建不行
