### ISSUE TITLE
miui调用相机拍完照确认时相机崩溃

### ISSUE THREAD

**Issue by litforest** [donglua/PhotoPicker#140]
报错： Permission Denial: opening provider  uid=10033) ....  that is not exported from uid 10036 
Uri photoFile = FileProvider.getUriForFile(this.mContext, authority, file)
好像是这个uri里的provider的问题。

**Comment by liujiangshuai** [comment]
android6.0 以上的系统，修改了权限机制， 拍照完成保存到手机 ，需要sd卡读写的权限，可参考：
http://blog.csdn.net/lmj623565791/article/details/50709663

**Comment by litforest** [comment]
不是权限的问题，miui的android版本是4.4.4(老实说我也没有6.0的miui机子)。只是在miui中出问题，我测试了华为的mate7和nexus5，两者的android版本都是6.0，并不会出现相机崩溃的情况。问题在于从provider获取的uri，我换了一个路径，就不会崩溃了。
