### ISSUE TITLE
微信版的MultiPickResultView控件有个Bug

### ISSUE THREAD

**Issue by MoneyNotFoundException** [donglua/PhotoPicker#146]
选择完成后，点击九宫格图片预览照片，点击右上角的删除按钮，删除完成后，如果点击物理返回键，则会将图片从九宫格删除，若点击左上角的返回键返回后，在预览时被删除的照片还是会显示在九宫格中，还望作者修复下，感谢！

**Comment by donglua** [comment]
@glassLake

**Comment by magic0908** [comment]
找到Titlebar的init方法，onClick的监听事件中，调用activity的finish之前，调用一次onBackPressed方法，这样点左上角的返回就可以正确删除了。不过这个方法我没有经过其他测试，还有待作者认证。

**Comment by donglua** [comment]
MultiPickResultView 不是这个项目的，这个问题关了。
