### ISSUE TITLE
为什么我导入后一直报glide有重复的 我找了多次都没有重复的，求解决

### ISSUE THREAD

**Issue by chen3441251** [donglua/PhotoPicker#150]
com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/bumptech/glide/gifdecoder/GifDecoder$BitmapProvider.class

**Comment by donglua** [comment]
是用aar包吗

```
    compile 'me.iwf.photopicker:PhotoPicker:0.9.0@aar'
```

**Comment by chen3441251** [comment]
不是 是由两个moudle 环信的用的是glide jar包 而这个photoPicker用的是依赖 导致用重复了 已经解决了 把jar删除了 也用了依赖
