### ISSUE TITLE
6.0权限申请改进建议

### ISSUE THREAD

**Issue by MoneyNotFoundException** [donglua/PhotoPicker#153]
6.0以上的机子申请权限时，用户若选中不再提示且拒绝权限，则无法再次打开PhotoPicker，希望作者将此情况考虑进去。

**Comment by onlynight** [comment]
申请权限的东西还是自己做好，因为权限请求的发起和处理都要在activity中完成。

**Comment by jounghu** [comment]
为什么我android 4.3点击相机打不开相机！没有反应

**Comment by MoneyNotFoundException** [comment]
@jounghu 检查你的AndroidManifest.xml里面有没有添加相机权限

**Comment by jounghu** [comment]
@MoneyNotFoundException 谢谢你，但是拍完照片之后，有2份在选择器中

**Comment by donglua** [comment]
试试新版本 0.9.5

**Comment by donglua** [comment]
用户若选中不再提示且拒绝权限，这种情况最好你自己判断，告诉用户为什么需要得到这个权限，这个不好做成通用的东西。
