### ISSUE TITLE
android 7.0 点击拍照崩溃

### ISSUE THREAD

**Issue by ghost** [donglua/PhotoPicker#167]
RT
android 5 没有这个问题；

**Comment by vito1** [comment]
我的手机是 HUAWEI Mate 9 ；权限已开

**Comment by rabbitquan** [comment]
compileSdkVersion = 25

**Comment by donglua** [comment]
安装 Demo 试试，不崩的话先参考 Demo

**Comment by rabbitquan** [comment]
这个账户是我，然后我运行demo是没有这个问题的，集成到项目里出现的问题，因为我把版本下降到24了，跟我项目保持一致！
