### ISSUE TITLE
能获取压缩后的图片吗 不然上传图片太大了

### ISSUE THREAD

**Issue by githubwxq** [donglua/PhotoPicker#172]

**Comment by donglua** [comment]
上传的时候再压缩吧，自己压一下~~

**Comment by KANGOD** [comment]
PhotoPicker 只负责提供一个包含 selectedPhotos 路径的 List，至于后续怎么处理这些路径，是显示、上传还是怎样，已经不是 PhotoPicker 的职责了。此 issue 似乎可以关闭。
