### ISSUE TITLE
如果我想隐藏预览界面的删除按钮，该怎么办？

### ISSUE THREAD

**Issue by sendtion** [donglua/PhotoPicker#182]
我只想预览，不想删除。

**Comment by donglua** [comment]
PhotoPreview.builder()
    .setPhotos(selectedPhotos)
    .setCurrentItem(position)
    **.setShowDeleteButton(false)**
    .start(MainActivity.this);

**Comment by sendtion** [comment]
我现在用的是0.8.5版本，我用着0.9.5刚打开的时候会卡顿一两秒才加载出来图片列表，旧版本就是秒开。这是怎么回事？
