### ISSUE TITLE
Folder chooser

### ISSUE THREAD

**Issue by vleango** [donglua/PhotoPicker#19]
Hello. Your library is great! Thank you.

Issue I have is with the "ALL IMAGE" folder chooser.
It repeats "ALL IMAGE", and "Pictures" for each taken picture. (After photo is taken from the camera)

i.e.

All image
All Image
All Image
Pictures
All Image
Pictures
All Image
Pictures
etc..

**Comment by donglua** [comment]
I moved *<code>listAdapter  = new PopupDirectoryListAdapter(getActivity(), directories);</code>* from *<code>onCreate</code>* to *<code>onCreateView</code>*, it seems to be fixed. #22
