### ISSUE TITLE
selected images data not show or open in fragment

### ISSUE THREAD

**Issue by rajam1215** [donglua/PhotoPicker#191]
selected images data not show or open in fragment, but if i use in activity its run perfectly but not in fragment how to solve. give me solution as soon as possible.

thanks

**Comment by adminwxd** [comment]
I also met the same problem, used fragment can't obtain the data in the callback

**Comment by rajam1215** [comment]
you have any solution for that

**Comment by lsyz0021** [comment]
like

 PhotoPicker.builder()
                .setPhotoCount(1)
                .setShowCamera(true)
                .setShowGif(false)
                .setPreviewEnabled(false)
                .start(mContext, mFragment, requestCode);

**Comment by rajam1215** [comment]
i use this already when use theis method

.start(mContext, mFragment, requestCode);

on fragment show error give error by android studio  u use fragment
acticvity..

**Comment by rajam1215** [comment]
con u show me how u take object of fragment

**Comment by rikutys** [comment]
I have the same problem here and i found out if i call the method and when it return the value it goes to Activity onActivityResult instead of Fragment. The method is in the Fragment therefore the getActivity() are Fragment Activity. 

public void initiateMultiPicker(View v){
        PhotoPicker.builder()
                .setPhotoCount(30)
                .setGridColumnCount(2)
                .start(getActivity());
    }

**Comment by rajam1215** [comment]
u have any solution

**Comment by rikutys** [comment]
Hi,

My solution was reopen the Fragment and i had tried it successful but it is
too troublesome. I had decided not to use fragment for the library.

**Comment by rajam1215** [comment]
I use on activity result in main activity for use intent data and then i use method of fragment in onacticity result. data is goes to fragment without problem. but method data null outside of method. so photoadapter,  recycler view give null error in method. fragment widget not work in this method. this library have list of bug . i suggest to dongula please solve that. as soon as possible.

**Comment by rajam1215** [comment]
Hi Guys i think I solve that issue. Its pretty freak in. please take onactivityresult method in MainActivity and do adapter notify or add images in array as well in activity. only the recycler touch event method use in fragment and take adapter and array static in main activity. and use in fragment statically in touch method and set adapter in onCreateView method statically. its run without any issue. because that library have some issue to give data in fragment. so further timing use this library that way. i think it is helpful for all those guy those are use that library

**Comment by rajam1215** [comment]
recyclerView = (RecyclerView) v.findViewById(R.id.cr_recycler_view);
        photoAdapter = new PhotoAdapter(getActivity(), selectedPhotos); // photoAdapter and selectedPhoto(array) is static that take in main activity 

        recyclerView.setLayoutManager(new StaggeredGridLayoutManager(4, OrientationHelper.VERTICAL));
        recyclerView.setAdapter(photoAdapter);

        recyclerView.addOnItemTouchListener(new RecyclerItemClickListener(getActivity(),
                new RecyclerItemClickListener.OnItemClickListener() {
                    @Override
                    public void onItemClick(View view, int position) {
                        if (photoAdapter.getItemViewType(position) == PhotoAdapter.TYPE_ADD) {
                            PhotoPicker.builder()
                                    .setPhotoCount(PhotoAdapter.MAX)
                                    .setShowCamera(true)
                                    .setPreviewEnabled(false)
                                    .setSelected(selectedPhotos)
                                    .start(getActivity());
                        } else {
                            PhotoPreview.builder()
                                    .setPhotos(selectedPhotos)
                                    .setCurrentItem(position)
                                    .start(getActivity());
                        }
                    }
                }));

rest do same as well as like activity library code

**Comment by junoprima** [comment]
can do help me show in fragment
`public class AddPhoto extends Fragment {

    private PhotoAdapter photoAdapter;

    private ArrayList<String> selectedPhotos = new ArrayList<>();


    public AddPhoto() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.add_photo, container, false);

        RecyclerView recyclerView = (RecyclerView) view.findViewById(R.id.addimg_view);
        photoAdapter = new PhotoAdapter(getContext(), selectedPhotos);

        recyclerView.setLayoutManager(new StaggeredGridLayoutManager(4, OrientationHelper.VERTICAL));
        recyclerView.setAdapter(photoAdapter);


        view.findViewById(R.id.button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                PhotoPicker.builder()
                        .setPhotoCount(9)
                        .setGridColumnCount(4)
                        .start(getActivity());
            }
        });


        recyclerView.addOnItemTouchListener(new RecyclerItemClick(getActivity(),
                new RecyclerItemClick.OnItemClickListener() {
                    @Override
                    public void onItemClick(View view, int position) {
                        if (photoAdapter.getItemViewType(position) == PhotoAdapter.TYPE_ADD) {
                            PhotoPicker.builder()
                                    .setPhotoCount(PhotoAdapter.MAX)
                                    .setShowCamera(true)
                                    .setPreviewEnabled(true)
                                    .setSelected(selectedPhotos)
                                    .start(getActivity());
                        } else {
                            PhotoPreview.builder()
                                    .setPhotos(selectedPhotos)
                                    .setCurrentItem(position)
                                    .start(getActivity());
                        }
                    }
                }));

        return view;
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        //Remove the below code from here

        if (resultCode == Activity.RESULT_OK &&
                (requestCode == PhotoPicker.REQUEST_CODE || requestCode == PhotoPreview.REQUEST_CODE)) {


            ArrayList<String> photos = null;
            Log.e("data", "size" + photos.size());
            if (data != null) {
                Log.e("Post Activity data","inside activity result");
                photos = data.getStringArrayListExtra(PhotoPicker.KEY_SELECTED_PHOTOS);
                Log.e("Post Activity data","size"+ photos.size());
            }
            selectedPhotos.clear();

                if (photos != null) {

                selectedPhotos.addAll(photos);
            }
            photoAdapter.notifyDataSetChanged();


        }
    }


}
`

**Comment by Eklett** [comment]
@junoprima 
`PhotoPicker.builder()
                                .setPhotoCount(PhotoAdapter.MAX)
                                .setShowCamera(true)
                                .setPreviewEnabled(true)
                                .setSelected(selectedPhotos)
                                .start(getActivity(), AddPhoto.this, PhotoPicker.REQUEST_CODE);`
