### ISSUE TITLE
与融云的provider冲突

### ISSUE THREAD

**Issue by xuminmin0405** [donglua/PhotoPicker#207]
<provider
    android:name="android.support.v4.content.FileProvider"
    android:authorities="您的应用包名.FileProvider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/rc_file_path" />
</provider>

**Comment by donglua** [comment]
最新版本已经解决这个问题，版本号是 0.9.9
