### ISSUE TITLE
two bugs

### ISSUE THREAD

**Issue by Loyea** [donglua/PhotoPicker#21]
* 选择图片后点击已经选择的图片查看详细，此时点击右上角的删除按钮，然后点击back退出查看详细页面，该图片仍旧存在。 只能通过点击删除后点击页面左上角的箭头退出才可删除成功。

* 崩溃问题，经测试，在删除 9/9，8/9，8/8，7/7 这四张图时会出现崩溃问题

**Comment by DroidNinja** [comment]
You need to set offscreenpagelimit of the viewpager to the maximum count. Currently, It is set to 5.

**Comment by donglua** [comment]
我删除了<code>pagerFragment.getViewPager().removeViewAt(index);</code>这行代码，看起来崩溃的问题已经好了

**Comment by Loyea** [comment]
第一个问题只要覆写一下onBackPressed即可 

~~~
	  @Override
	public void onBackPressed() {
	  Intent intent = new Intent();
      intent.putExtra(PhotoPickerActivity.KEY_SELECTED_PHOTOS, pagerFragment.getPaths());
      setResult(RESULT_OK, intent);  
      this.finish();
	}
~~~
