### ISSUE TITLE
0.2.4选择单张图片bug以及相册数量增多bug

### ISSUE THREAD

**Issue by wangkunlin** [donglua/PhotoPicker#27]
先勾选一张图片，再次点击当前被勾选的图片，右上角完成消失，但是当前图片的勾还是存在的，并且再次点勾没有任何反映。

**Comment by wangkunlin** [comment]
拍照后，相册数量依然会增多。

**Comment by donglua** [comment]
勾选的问题是只选择一张的时候才是这样吧。

**Comment by donglua** [comment]
好的，我可以重现出问题了。。  刚才又更新一个版本，这应该下可以了

**Comment by wangkunlin** [comment]
是在选一张的时候的，不应该是点击已经勾选的勾就应该取消勾选么？

**Comment by donglua** [comment]
嗯，现在已经改了，因为当时想的是如果只选一张，那么不想选了点返回就是了。
