### ISSUE TITLE
可以移除无用的资源文件ic_launcher.png吗？

### ISSUE THREAD

**Issue by cmeiyuan** [donglua/PhotoPicker#29]
可以移除无用的资源文件ic_launcher.png吗？

因为会导致资源文件冲突，ic_launcher.png: Original is here.

主工程的ic_launcher.png可以重命名，但是其他第三方类库也没有移除ic_launcher.png，就比较难解决了。所以帮忙移除一下ic_launcher.png

**Comment by donglua** [comment]
已删

**Comment by cmeiyuan** [comment]
thanks
