### ISSUE TITLE
希望加入对网络图片预览的支持

### ISSUE THREAD

**Issue by jing-wu** [donglua/PhotoPicker#33]
使用此组件进行图片选择并发布内容后，再次编辑时，内容图片都是从网络上加载以供编辑的，这时图片预览组件就没法使用了

**Comment by donglua** [comment]
目前是支持的，传图片路径和图片url地址都是可以显示的

**Comment by jing-wu** [comment]
谢谢

现在唯一使用上的问题就是#31，这个我用了几个机器（moto x 5.1，三星9100 4.4，sony lt26i 4.4），都是能重现的。打开选择器，快速往下滑动，点击一张缩略图还未生成（或刚生成了模糊的缩略图）的图片，打开了预览页面，但是图片一直无法加载。

**Comment by donglua** [comment]
好，我周末再看看。
