### ISSUE TITLE
图片无法预览的bug

### ISSUE THREAD

**Issue by jing-wu** [donglua/PhotoPicker#35]
#31问题出现的几率小了，但依旧存在，目前只在4.1.2的lt26i上重现了。

现在的问题主要是，用上述机器打开图片选择器，不做任何操作，待缩略图加载完毕，点击一张图片，预览页可能显示出这张图片，也可能一直显示默认图片（如下图），无法预览

![lt26i_1257-77636 2 b 1 96jwu08312015143736](https://cloud.githubusercontent.com/assets/6805536/9573338/e02ba14c-4fed-11e5-98c3-1c37e9525a59.png)

**Comment by xiaozhi003** [comment]
不知道作者解决了这个问题没有 @donglua

**Comment by wangkunlin** [comment]
@xiaozhi003 
```java
Glide.with(context).load(path).placeholder(R.drawable.source_no_data).override(800, 800)
                .thumbnail(0.44f).dontAnimate()
                .error(R.drawable.source_no_data).into(imageView);
```
我是这样写的。你试试。

**Comment by xiaozhi003** [comment]
我把Glide换成了universalimageloader效果好多了而且很顺畅，唯一的不足就是不能动态显示gif图，不过对于这个场景也是无足轻重。Glide没用过不知道问题出在哪里，而且滑动久了也会卡，改成你那样的偶尔还是会出现问题，不过还是谢谢了 @wangkunlin 。以后有时间会看看Glide，也希望作者修复一下这个bug，又或者说这是Glide本身的问题，没有细研究也不敢妄加猜测了 ：)

**Comment by wangkunlin** [comment]
@xiaozhi003 我也是问了glide的作者，他说加dontanimate就行。

**Comment by donglua** [comment]
我更新了一个版本，把dontanimate加上了

**Comment by lennonliuyong** [comment]
我这边依然存在这个问题，看源码dontanimate也存在。
小米4手机
