### ISSUE TITLE
相册重复问题

### ISSUE THREAD

**Issue by xiaozhi003** [donglua/PhotoPicker#40]
我发现使用该库会出现很多重复的相册；对比的微信的图片选择他会把相同名称的相册合并，于是乎猜测作者没有过滤相同名字的相册；不过看了代码作者还是比较了，但是仍然有大量相同的名字的相册没有合并；发现原来是me.iwf.photopicker.entity.PhotoDirectory.java实体类中，重写的equal方法也加入了id的比较，修改equal方法只对name进行比较；改过之后和微信相册基本一致，希望作者修复；

**Comment by donglua** [comment]
这个重复的相册是手机相册本来就是重复的文件夹吗 还是这个库显示的问题？

**Comment by xiaozhi003** [comment]
好吧，其实不算是bug；确实是手机本身有很多相同名称的相册但是路径不同；微信是将他自动合并了，当然不合并也没有错；只是我的手机上看到就会有十几个相同的相册，相信其他人也可能会遇到这样的问题；不过作者的库还是不错的，遇到需求我们自行修改就好了；再此我只是提个建议也谢谢作者的回复；
