### ISSUE TITLE
为什么点击全部图片(ALL IMAGES)那里不能弹出文件夹选择呢

### ISSUE THREAD

**Issue by eling13** [donglua/PhotoPicker#42]
华为机子测试的，麻烦up主看下~~

还有预览时，图片可滑上滑下的，左右滑动切换上/下一张的时候图片有好些情况会不居中出现，大部分会出现在底部

**Comment by donglua** [comment]
好的~ 我再找机子测看看

**Comment by eling13** [comment]
up主测试完毕了没？ 有没有这样的情况，修复了？

**Comment by navyifanr** [comment]
@donglua po主，编译版本一定要23以上吗？低版本好像用不了，22也不行

**Comment by navyifanr** [comment]
@donglua 楼主，编译版本一定要23以上吗？低版本好像不行，22不行

**Comment by donglua** [comment]
* 我用华为荣耀是可以弹出文件夹的（抱歉，这么久才回复...）
* 不居中的问题已经修复了
