### ISSUE TITLE
查看图片问题

### ISSUE THREAD

**Issue by xiaotianyilang** [donglua/PhotoPicker#60]
查看某些图片的时候图片会显示在scrollview的底部而不是居中显示，这样会造成一下子看不全的问题

**Comment by Loyea** [comment]
倒不是图片在scrollview的底部，而是图片上面有空白部分，这有点莫名其妙

另外查看大图手势缩放也有问题。

**Comment by bethinner** [comment]
这可问题挺久了，作者好像都没出现啊

**Comment by Loyea** [comment]
我用回去年的版本了， 去年7月刚开始用的时候没这些bug.

**Comment by donglua** [comment]
我修复了。可以用最新的版本。
