### ISSUE TITLE
6.0调用PhotoPickerIntent开启PhotoPickerActivity页面崩溃

### ISSUE THREAD

**Issue by bethinner** [donglua/PhotoPicker#61]
I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
 I/HwCust: Constructor found for class android.widget.HwCustTextViewImpl
 I/Process: Sending signal. PID: 13914 SIG: 9
 I/HwCust: Constructor found for class android.widget.HwCustTextViewImpl
 I/HwCust: Constructor found for class android.widget.HwCustTextViewImpl
 E/HAL: load: id=gralloc != hmi->id=gralloc
 E/HAL: load: id=gralloc != hmi->id=gralloc
 I/OpenGLRenderer: Initialized EGL, version 1.4
 W/OpenGLRenderer: load: so=/system/lib64/libhwuibp.so
                                                                    dlopen failed: library "/system/lib64/libhwuibp.so" not found
W/OpenGLRenderer: Initialize Binary Program Cache: Load Failed
 E/HAL: load: id=gralloc != hmi->id=gralloc

手机是6.0的华为荣耀，别的手机没试过

**Comment by huahongyang** [comment]
我也遇到这个问题

**Comment by donglua** [comment]
试一下最新版本。。
