### ISSUE TITLE
通过它读取到的图片和系统相册的不一致呢

### ISSUE THREAD

**Issue by lpslpsl** [donglua/PhotoPicker#63]
或者说是有时候读取的图片图库已经不存在。比如被删除了。但是用它的时候似乎依然在，但是用做bitmap直接bitmap.decodeFile拿到的为null

**Comment by donglua** [comment]
这是什么手机上出现的

**Comment by lpslpsl** [comment]
。。我用的夜神模拟器。我搜了一下大概是说因为删除了文件但是缩略图还在的原因嘛
