### ISSUE TITLE
Removing Text At Bottom Of Camera Icon

### ISSUE THREAD

**Issue by EmreSURK** [donglua/PhotoPicker#69]
The examle on Google Play Sote have no text at bottom of camera icon.
But in my application there is a text at bottom of camera icon. I could not able to change or remove it.
Thanks.
<img width="713" alt="screen shot 2016-05-04 at 14 55 25" src="https://cloud.githubusercontent.com/assets/9450430/15013453/5f4226cc-1208-11e6-9e68-0da5e72bd1c3.png">

**Comment by donglua** [comment]
Try latest version ~
