### ISSUE TITLE
加载动态图编译报错

### ISSUE THREAD

**Issue by Tryking** [donglua/PhotoPicker#71]
编译的时候直接报错

Exception failed for task ':app:transformClassedWithJarMergingFor_DebugDebug'.
>com.android.build.api.transform.TransformException:java.util.zip.ZipException:duplicate entry: com/bumptech/glide/gifdecoder/GifDecoder$BitmapProvider.class

然后把Glide那个三方插件给移除后可以编译通过

应该是加载动态图那里有点儿问题，求donglua哥给解答下。

**Comment by donglua** [comment]
引入的包重复了吧，大概是Glide的依赖写多了一次

**Comment by Tryking** [comment]
是不是你的jar包里面引入Glide包了，所以我不需要引入了呢？

**Comment by donglua** [comment]
Jar包里有，不需要引入；用aar包就要引入其它的依赖，像这样：
        
    dependencies {
        compile 'me.iwf.photopicker:PhotoPicker:0.8.1@aar'

        compile 'com.android.support:appcompat-v7:23.1.1'
        compile 'com.android.support:recyclerview-v7:23.1.1'
        compile 'com.android.support:design:23.1.1'
        compile 'com.nineoldandroids:library:2.4.0'
        compile 'com.github.bumptech.glide:glide:3.6.0'
    }

**Comment by Tryking** [comment]
嗯嗯，谢谢啦，麻烦你啦！
