### ISSUE TITLE
选择图片界面，旋转屏幕，报错闪退

### ISSUE THREAD

**Issue by jing-wu** [donglua/PhotoPicker#75]
在选择图片的宫格界面，旋转屏幕，报空指针
![qq20160526-0](https://cloud.githubusercontent.com/assets/6805536/15567408/db58c098-2358-11e6-9b4e-9bfe18c58aae.png)

**Comment by jing-wu** [comment]
更新到最新的0.8.3，在选择照片界面旋转屏幕，不闪退了，但是旋转之后，页面上的图片都没了，显示为0张

旋转之前：
![screenshot_2016-06-27-11-52-31](https://cloud.githubusercontent.com/assets/6805536/16370447/32853676-3c72-11e6-9a0b-b4ee3fd20c90.png)


旋转之后：
![screenshot_2016-06-27-11-52-39](https://cloud.githubusercontent.com/assets/6805536/16370338/56efd382-3c71-11e6-84e3-824b314054a5.png)

**Comment by donglua** [comment]
这个有点坑。。是```Fragment```生命周期的问题，我暂时还没有好的解决方案。我再调一调，下个版本会改好。
