### ISSUE TITLE
在VIVO手机用不了呢，图片都显示不出来

### ISSUE THREAD

**Issue by leonck** [donglua/PhotoPicker#76]
在VIVO手机用不了呢，图片都显示不出来 我是用优测云手机测试的，图片都是裂图

**Comment by donglua** [comment]
我去优测试了一下，它本身的图片确实是显示不出来的。。然后我打开它的摄像头拍出来的是可以显示的。

**Comment by donglua** [comment]
![image](https://cloud.githubusercontent.com/assets/3875265/16146407/6b69587e-34b0-11e6-8cb5-fd08dcfb553d.png)

**Comment by Drizzlezhang** [comment]
vivo手机本身的图片都不能展示，路径都拿到了，这是什么问题？
