### ISSUE TITLE
PhotoPickerFragment打开崩溃

### ISSUE THREAD

**Issue by ToastJun** [donglua/PhotoPicker#77]
photoGridAdapter = new PhotoGridAdapter(getContext(), directories, column);

没有找到 getContext()方法

**Comment by izhangxb** [comment]
你没有添加：
compile 'com.android.support:appcompat-v7:23.1.1'
这个依赖。

**Comment by ToastJun** [comment]
我之前在使用的时候 是这样添加的 compile 'com.android.support:appcompat-v7:22.+'
使用的时候也一直没有报错，今天在使用的时候突然就报错了 而且我切回到我自己之前的版本也能编译过 就觉得非常奇怪

**Comment by donglua** [comment]
今天遇到这个问题了，代码用是22.2.0的 support 包，Fragment没有```getContext()```方法。。 用23以上的可以
