### ISSUE TITLE
点击相机报错

### ISSUE THREAD

**Issue by Lans** [donglua/PhotoPicker#83]
06-16 10:19:00.176 1220-1220/me.iwf.PhotoPickerDemo W/System.err: java.io.IOException: open failed: EACCES (Permission denied)
06-16 10:19:00.178 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at java.io.File.createNewFile(File.java:941)
06-16 10:19:00.179 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at java.io.File.createTempFile(File.java:1006)
06-16 10:19:00.179 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at me.iwf.photopicker.utils.ImageCaptureManager.createImageFile(ImageCaptureManager.java:44)
06-16 10:19:00.179 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at me.iwf.photopicker.utils.ImageCaptureManager.dispatchTakePictureIntent(ImageCaptureManager.java:61)
06-16 10:19:00.179 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at me.iwf.photopicker.fragment.PhotoPickerFragment$4.onClick(PhotoPickerFragment.java:158)
06-16 10:19:00.179 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at me.iwf.photopicker.adapter.PhotoGridAdapter$1.onClick(PhotoGridAdapter.java:79)
06-16 10:19:00.179 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at android.view.View.performClick(View.java:4909)
06-16 10:19:00.179 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at android.view.View$PerformClick.run(View.java:20390)
06-16 10:19:00.179 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
06-16 10:19:00.179 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
06-16 10:19:00.179 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at android.os.Looper.loop(Looper.java:194)
06-16 10:19:00.184 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5803)
06-16 10:19:00.184 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-16 10:19:00.184 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-16 10:19:00.184 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010)
06-16 10:19:00.184 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
06-16 10:19:00.184 1220-1220/me.iwf.PhotoPickerDemo W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
06-16 10:19:00.185 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at libcore.io.Posix.open(Native Method)
06-16 10:19:00.185 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-16 10:19:00.185 1220-1220/me.iwf.PhotoPickerDemo W/System.err:     at java.io.File.createNewFile(File.java:934)
06-16 10:19:00.185 1220-1220/me.iwf.PhotoPickerDemo W/System.err: 	... 15 more

**Comment by donglua** [comment]
```Permission denied```
是不是没有声明相关权限

**Comment by Lans** [comment]
权限声明了也如此
