### ISSUE TITLE
REQUEST_CODE自定义

### ISSUE THREAD

**Issue by jing-wu** [donglua/PhotoPicker#87]
更新到最新的0.8.3，发现REQUEST_CODE无法自定义了，变成了固定的233.

有这样的业务场景，一个页面有多处要选择图片的地方（不确定具体个数），用循环为每个地方绑定一个点击选择图片的事件，用的是各自唯一的REQUEST_CODE（使用随机值，生成并维护起来），这样在onActivityResult中就可以区分出是哪边点击了，图片可以显示到该显示的地方。

现在新版固定了REQUEST_CODE，在这种场景下，无法满足需求

**Comment by donglua** [comment]
支持自定义的。
```java
PhotoPicker.builder()
    .setPhotoCount(9)
    .start(this, REQUEST_CODE);
```

**Comment by jing-wu** [comment]
不好意思，是我粗心了，没有注意。
