### ISSUE TITLE
NoSuchMethodError依然重现

### ISSUE THREAD

**Issue by lhholylight** [donglua/PhotoPicker#95]
java.lang.NoSuchMethodError: No virtual method getContext()Landroid/content/Context; in class Lme/iwf/photopicker/fragment/PhotoPickerFragment; or its super classes (declaration of 'me.iwf.photopicker.fragment.PhotoPickerFragment' appears in /data/app/com.nake.app-1/base.apk)

**Comment by donglua** [comment]
用23以上的support包吧
