### ISSUE TITLE
怎么过滤掉已经损坏的图片？

### ISSUE THREAD

**Issue by 416679828** [donglua/PhotoPicker#99]
如题

**Comment by hqucsx** [comment]
MediaStoreHelper中加上文件判断
` 
File file = new File(path);
if (file.exists() && file.length() > 0) {
          PhotoDirectory photoDirectory = new PhotoDirectory();
          photoDirectory.setId(bucketId);
....
}`

**Comment by Sum41forever** [comment]
删除的图片，还是能预览，并且能选中返回，但是在上传的时候，file为空上传失败

**Comment by zhoujuanjuan** [comment]
@donglua 修改完了并没有过滤掉损坏图片，用hqucsx方法可以

**Comment by 416679828** [comment]
Thanks @hqucsx

**Comment by q805699513** [comment]
@hqucsx 这种方法只能过滤file.length() > 0的文件，如果有个.jpg的文件，但是下载不完整的图片文件还是会无法显示，用BitmapFactory可以判断，但是效率低一些
